routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('products', 'ProductController');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model {
    
    protected $fillable = [
        'name', 'short', 'body',
    ];
    
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Product;
use App\Http\Requests\ProductRequest;

class ProductController extends Controller
{
    
    public function index() {
        $products = Product::orderBy('id', 'ASC')->paginate();
        return view('products.index', compact('products'));
    }


    public function create() {
        return view('products.create');
    }


    public function store(ProductRequest $request) {
        
        $product = new Product;
        $product->name = $request->name;
        $product->short = $request->short;
        $product->body = $request->body;

        $product->save();
        
        return redirect()->route('products.show', ['id' => $product->id])->with('info', 'El Producto fué guardado satisfactoriamente.');

    }


    public function edit($id) {
        $product = Product::find($id);
        return view('products.edit', compact('product'));
    }


    public function update(ProductRequest $request, $id) {
        
        $product = Product::find($id);
        $product->name = $request->name;
        $product->short = $request->short;
        $product->body = $request->body;

        $product->save();
        
        return redirect()->route('products.show', ['id' => $product->id])->with('info', 'El Producto fué actualizado satisfactoriamente.');

    }


    public function show($id) {
        $product = Product::find($id);
        return view('products.show', compact('product'));
    }


    public function destroy($id) {
        $product = Product::find($id);
        $product->delete();

        return back()->with('info', 'El Producto fué eliminado satisfactoriamente');
    }
    
}

resources/views/layouts/layout.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>First CRUD | Laravel 5.4</title>

    <!-- Bootstrap -->
    <link href="{{ url('assets/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="{{ url('assets/bootstrap/js/html5shiv.min.js') }}"></script>
      <script src="{{ url('assets/bootstrap/js/respond.min.js') }}"></script>
    <![endif]-->
  </head>
  <body>
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <h1 class="jumbotron text-center">My First CRUD</h1>
            </div>

            <div class="row">
                <div class="col-sm-8 col-sm-offset-2">
                    @include('products.fragment.info')
                    @include('products.fragment.error')
                </div>

                @yield('content')
            </div>
        </div>
    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{{ url('assets/bootstrap/js/jquery.min.js') }}"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{{ url('assets/bootstrap/js/bootstrap.min.js') }}"></script>
  </body>
</html>

resources/views/products/create.blade.php
@extends('layouts.layout')

@section('content')
    <div class="col-sm-8 col-sm-offset-2" style="margin-bottom:20px;">
        <h2 style="margin-bottom:30px;">
            Crear un nuevo Producto
        </h2>

        {!! Form::open(['route' => 'products.store']) !!}

             @include('products.fragment.form')

        {!! Form::close() !!}
        
    </div>
@endsection

resources/views/products/edit.blade.php
@extends('layouts.layout')

@section('content')
    <div class="col-sm-8 col-sm-offset-2" style="margin-bottom:20px;">
        <h2 style="margin-bottom:30px;">
            Editar un Producto
        </h2>

        {!! Form::model($product, ['route' => ['products.update', $product->id], 'method' => 'PUT']) !!}

             @include('products.fragment.form')

        {!! Form::close() !!}

    </div>
@endsection

resources/views/products/fragment/error.blade.php
@if(count($errors))
    <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">
            &times;
        </button>

        <ul>
            @foreach($errors->all() as $error)
                <li>
                    {{ $error }}
                </li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/products/fragment/form.blade.php
<div class="form-group">
    {!! Form::label('name', 'Nombre del Producto') !!}
    {!! Form::text('name', null, ['class' => 'form-control', 'placeholder' => 'Ingrese el nombre del producto']) !!}
</div>

<div class="form-group">
    {!! Form::label('short', 'Descripción breve del Producto') !!}
    {!! Form::text('short', null, ['class' => 'form-control', 'placeholder' => 'Ingrese la descripción breve del producto']) !!}
</div>

<div class="form-group">
    {!! Form::label('body', 'Descripción larga del Producto') !!}
    {!! Form::textarea('body', null, ['class' => 'form-control', 'placeholder' => 'Ingrese la descripción larga del producto']) !!}
</div>

<div class="form-group text-right">
    <a href="{{ route('products.index') }}" class="btn btn-danger">CANCELAR</a>
    {!! Form::submit('GUARDAR', ['class' => 'btn btn-primary']) !!}
</div>

resources/views/products/fragment/info.blade.php
@if(Session::has('info'))
    <div class="alert alert-info">
        <button type="button" class="close" data-dismiss="alert">
            &times;
        </button>
        {{ Session::get('info') }}
    </div>
@endif

resources/views/products/index.blade.php
@extends('layouts.layout')

@section('content')
    <div class="col-sm-8 col-sm-offset-2" style="margin-bottom:20px;">
        <h2 style="margin-bottom:30px;">
            Listado de Productos
            <a href="{{ route('products.create') }}" class="btn btn-primary btn-sm pull-right">Nuevo Producto</a>
        </h2>

        <table class="table table-hover table-striped table-condensed">
            <thead>
                <h4>
                    <td width="35px"><h4 class="text-center">#</h4></td>
                    <td><h4>Nombre del Producto</h4></td>
                    <td colspan="3"><h4 class="text-center">Acción</h4></td>
                </tr>
            </thead>
            <tbody>
                @foreach($products as $product)
                    <tr>
                        <td>{{ $product->id }}</td>
                        <td>
                            <strong>{{ $product->name }}</strong>
                            <small>{{ $product->short }}</small>
                        </td>
                        <td style="vertical-align:middle;"><a href="{{ route('products.show', $product->id) }}" class="btn btn-success btn-xs">ver</a></td>
                        <td style="vertical-align:middle;"><a href="{{ route('products.edit', $product->id) }}" class="btn btn-primary btn-xs">editar</a></td>
                        <td style="vertical-align:middle;">
                            <form action="{{ route('products.destroy', $product->id) }}" method="POST">
                                {{ csrf_field() }}
                                <input type="hidden" name="_method" value="DELETE" />
                                <button class="btn btn-danger btn-xs">borrar</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>

        {!! $products->render() !!}
    </div>
@endsection

resources/views/products/show.blade.php
@extends('layouts.layout')

@section('content')
    <div class="col-sm-8 col-sm-offset-2">
        <div class="button-group text-right">
            <a href="{{ route('products.index') }}" class="btn btn-default btn-sm">Regresar</a>
            <a href="{{ route('products.edit', $product->id) }}" class="btn btn-warning btn-sm">Editar</a>
        </div>
        <h2>
            {{ $product->name }}
        </h2>

        <p>
            {{ $product->short }}
        </p>

        {!! $product->body !!}
    </div>
@endsection